import { expect, test } from '@playwright/test'

test('initializes the platform and switches the embedded interface language', async ({ page }) => {
  await page.goto('/')
  await page.locator('#username').fill('e2e-admin')
  await page.locator('#displayName').fill('E2E Admin')
  await page.locator('#password').fill('e2e-password')
  await page.getByRole('button', { name: '初始化 DB Mock' }).click()
  await expect(page.getByText('总览', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('完成首次数据库部署', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '跳到主要内容' })).toHaveAttribute('href', '#main-content')
  await expect(page.getByRole('button', { name: '账号菜单' })).toBeVisible()
  await expect(page.getByText('系统设置', { exact: true })).toBeVisible()
  await page.locator('.page-header').getByRole('button', { name: '接入主机' }).click()
  const hostDialog = page.getByRole('dialog', { name: '接入主机' })
  await expect(hostDialog).toBeVisible()
  await expect(hostDialog.getByLabel('SSH 用户')).toHaveValue('')
  await expect(hostDialog.getByLabel('私钥口令')).toHaveValue('')
  await expect(hostDialog.getByRole('button', { name: /保\s*存/ })).toBeDisabled()
  await expect(hostDialog.getByText('保存前请测试 SSH 连接，平台会确认主机身份并检测系统、Docker 与可用资源。')).toBeVisible()
  await expect(hostDialog.getByLabel('托管数据根目录')).not.toBeVisible()
  await hostDialog.getByText('高级设置', { exact: true }).click()
  await expect(hostDialog.getByLabel('托管数据根目录')).toHaveValue('/opt/dbmock')
  await hostDialog.getByRole('button', { name: '关闭', exact: true }).click()

  await page.goto('/projects')
  await expect(page.getByText('尚未创建项目。项目可用于按团队、环境或业务线组织主机和数据库。')).toBeVisible()
  await page.locator('.page-header').getByRole('button', { name: '创建' }).click()
  let projectDialog = page.getByRole('dialog', { name: '创建' })
  await projectDialog.getByLabel('名称').fill('E2E Project')
  await projectDialog.getByLabel('描述').fill('Must not leak into the next project')
  await projectDialog.getByRole('button', { name: /保\s*存/ }).click()
  await expect(page.getByRole('heading', { name: 'E2E Project' })).toBeVisible()
  await page.getByRole('button', { name: '编辑 E2E Project' }).click()
  projectDialog = page.getByRole('dialog', { name: '编辑' })
  await expect(projectDialog.getByLabel('描述')).toHaveValue('Must not leak into the next project')
  await projectDialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.locator('.page-header').getByRole('button', { name: '创建' }).click()
  projectDialog = page.getByRole('dialog', { name: '创建' })
  await expect(projectDialog.getByLabel('名称')).toHaveValue('')
  await expect(projectDialog.getByLabel('描述')).toHaveValue('')
  await projectDialog.getByRole('button', { name: '关闭', exact: true }).click()

  await page.goto('/instances')
  await expect(page.getByText('尚未创建数据库。接入可用主机后，即可从目录选择模板部署。')).toBeVisible()
  await expect(page.locator('.page-header').getByRole('button', { name: '接入主机' })).toBeVisible()
  await page.route('**/api/v1/hosts', async (route) => route.fulfill({ json: { items: [{ id: '11111111-1111-4111-8111-111111111111', name: 'E2E Host', status: 'online', architecture: 'arm64', cpuCount: 8, memoryBytes: 17179869184 }] } }))
  await page.goto('/instances?create=1')
  const createInstanceDrawer = page.getByRole('dialog', { name: '创建数据库' })
  await expect(createInstanceDrawer).toBeVisible()
  await expect(createInstanceDrawer.getByRole('button', { name: '上一步' })).toBeDisabled()
  await expect(createInstanceDrawer.getByRole('button', { name: '下一步' })).toBeVisible()
  const templateSelect = createInstanceDrawer.getByLabel('模板 / 版本')
  await templateSelect.click()
  await templateSelect.press('ArrowDown')
  await templateSelect.press('Enter')
  await createInstanceDrawer.getByRole('button', { name: '下一步' }).click()
  await createInstanceDrawer.getByLabel('名称').fill('E2E Database')
  await createInstanceDrawer.getByRole('button', { name: '下一步' }).click()
  await expect(createInstanceDrawer.getByLabel('CPU')).not.toHaveValue('')
  await createInstanceDrawer.getByRole('button', { name: '下一步' }).click()
  await createInstanceDrawer.getByLabel('额外环境变量（JSON）').fill('[]')
  await createInstanceDrawer.getByRole('button', { name: '下一步' }).click()
  await expect(createInstanceDrawer.getByText('请输入合法的 JSON 对象，例如 {"TZ":"Asia/Shanghai"}')).toBeVisible()
  await createInstanceDrawer.getByLabel('额外环境变量（JSON）').fill('{"TZ":"Asia/Shanghai"}')
  await createInstanceDrawer.getByRole('button', { name: '下一步' }).click()
  await expect(createInstanceDrawer.getByText('创建实例会启动持久化任务。你可以安全离开本页，并在任务中心跟踪进度。')).toBeVisible()
  await expect(createInstanceDrawer.getByRole('button', { name: '上一步' })).toBeEnabled()
  await createInstanceDrawer.getByRole('button', { name: '上一步' }).click()
  await expect(createInstanceDrawer.getByLabel('额外环境变量（JSON）')).toHaveValue('{"TZ":"Asia/Shanghai"}')
  await createInstanceDrawer.getByRole('button', { name: /取\s*消/ }).click()
  await page.unroute('**/api/v1/hosts')

  await page.goto('/images')
  await expect(page.getByText('尚未上传离线镜像。上传 docker save 导出的镜像包，即可在无法访问镜像仓库时部署数据库。')).toBeVisible()
  await expect(page.getByRole('button', { name: '上传离线镜像' }).first()).toBeVisible()

  await page.goto('/catalog')
  await expect(page.locator('.database-icon')).toHaveCount(19)
  await expect(page.getByRole('img', { name: 'MySQL' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'PostgreSQL' })).toBeVisible()
  const cardBaselines = await page.evaluate(() => Array.from(document.querySelectorAll('.template-card')).slice(0, 2).map((card) => {
    const top = (selector: string) => Math.round(card.querySelector(selector)?.getBoundingClientRect().top ?? 0)
    return ['.template-card-title-row', '.template-card-description', '.template-card-tags', '.template-meta', '.ant-card-actions'].map(top)
  }))
  expect(cardBaselines[0]).toEqual(cardBaselines[1])
  await page.getByRole('searchbox', { name: '搜索' }).fill('definitely-no-such-database')
  await expect(page.getByText('没有匹配的数据库模板。请调整搜索词或筛选条件。')).toBeVisible()
  await page.getByRole('button', { name: '清除筛选' }).click()
  await expect(page.locator('.database-icon')).toHaveCount(19)
  await page.locator('.template-card').first().getByRole('button', { name: '创建' }).click()
  const redirectedHostDialog = page.getByRole('dialog', { name: '接入主机' })
  await expect(redirectedHostDialog).toBeVisible()
  await expect(page).toHaveURL(/\/hosts$/)
  await redirectedHostDialog.getByRole('button', { name: '关闭', exact: true }).click()

  const taskID = '22222222-2222-4222-8222-222222222222'
  await page.route(`**/api/v1/tasks/${taskID}`, async (route) => route.fulfill({ json: { id: taskID, kind: 'host_probe', status: 'running', resourceType: 'host', resourceId: '11111111-1111-4111-8111-111111111111', progress: 35, stage: 'probe', message: 'checking_host_and_template', cancelable: true, cancelAsked: false, attempts: 1, createdAt: new Date().toISOString() } }))
  await page.route(`**/api/v1/tasks/${taskID}/logs`, async (route) => route.fulfill({ json: { items: [] } }))
  await page.goto(`/tasks?task=${taskID}`)
  const taskDrawer = page.getByRole('dialog', { name: /检测主机 · 22222222/ })
  await expect(taskDrawer).toBeVisible()
  await taskDrawer.getByRole('button', { name: '关闭', exact: true }).click()
  await expect(page).toHaveURL(/\/tasks$/)
  await page.unroute(`**/api/v1/tasks/${taskID}`)
  await page.unroute(`**/api/v1/tasks/${taskID}/logs`)

  await page.goto('/audit')
  await page.locator('.page-header').getByRole('button', { name: '清理' }).click()
  let clearAuditDialog = page.getByRole('dialog', { name: '清理' })
  await clearAuditDialog.getByLabel('输入 CLEAR 以确认').fill('CLEAR')
  await expect(clearAuditDialog.getByRole('button', { name: /确\s*定/ })).toBeEnabled()
  await clearAuditDialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.locator('.page-header').getByRole('button', { name: '清理' }).click()
  clearAuditDialog = page.getByRole('dialog', { name: '清理' })
  await expect(clearAuditDialog.getByLabel('输入 CLEAR 以确认')).toHaveValue('')
  await expect(clearAuditDialog.getByRole('button', { name: /确\s*定/ })).toBeDisabled()
  await clearAuditDialog.getByRole('button', { name: '关闭', exact: true }).click()
  await page.goto('/')

  await page.getByRole('button', { name: 'English' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'en-US')
  await expect(page.getByText('Dashboard', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Complete your first database deployment', { exact: true })).toBeVisible()
  await expect(page.locator('.page-header').getByRole('button', { name: 'Add host' })).toBeVisible()
  await page.goto('/hosts')
  await expect(page.getByText('Direct SSH only. Linux can optionally install Docker; macOS requires Docker Desktop.')).toBeVisible()

  await page.getByRole('button', { name: '简体中文' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page.getByText('主机', { exact: true }).first()).toBeVisible()
  const health = await page.request.get('/api/v1/health')
  expect(health.ok()).toBeTruthy()
})
