import { expect, test } from '@playwright/test'

test('initializes the platform and switches the embedded interface language', async ({ page }) => {
  await page.goto('/')
  await page.locator('#username').fill('e2e-admin')
  await page.locator('#displayName').fill('E2E Admin')
  await page.locator('#password').fill('e2e-password')
  await page.getByRole('button', { name: '初始化 DB Mock' }).click()
  await expect(page.getByText('总览', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('完成首次数据库部署', { exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: '跳到主要内容' })).toHaveAttribute('href', '#main-content')
  await expect(page.getByRole('button', { name: '账号菜单' })).toBeVisible()
  await expect(page.getByText('系统设置', { exact: true })).toBeVisible()
  await page.locator('.page-header').getByRole('button', { name: '接入主机' }).click()
  const hostDialog = page.getByRole('dialog', { name: '接入主机' })
  await expect(hostDialog).toBeVisible()
  await expect(hostDialog.getByLabel('SSH 用户')).toHaveValue('')
  await expect(hostDialog.getByLabel('私钥口令')).toHaveValue('')
  await expect(hostDialog.getByRole('button', { name: /保\s*存/ })).toBeVisible()
  await hostDialog.getByRole('button', { name: '关闭' }).click()

  await page.goto('/projects')
  await expect(page.getByText('尚未创建项目。项目可用于按团队、环境或业务线组织主机和数据库。')).toBeVisible()
  await page.locator('.page-header').getByRole('button', { name: '创建' }).click()
  let projectDialog = page.getByRole('dialog', { name: '创建' })
  await projectDialog.getByLabel('名称').fill('E2E Project')
  await projectDialog.getByLabel('描述').fill('Must not leak into the next project')
  await projectDialog.getByRole('button', { name: /保\s*存/ }).click()
  await expect(page.getByRole('heading', { name: 'E2E Project' })).toBeVisible()
  await page.getByRole('button', { name: '编辑 E2E Project' }).click()
  projectDialog = page.getByRole('dialog', { name: '编辑' })
  await expect(projectDialog.getByLabel('描述')).toHaveValue('Must not leak into the next project')
  await projectDialog.getByRole('button', { name: '关闭' }).click()
  await page.locator('.page-header').getByRole('button', { name: '创建' }).click()
  projectDialog = page.getByRole('dialog', { name: '创建' })
  await expect(projectDialog.getByLabel('名称')).toHaveValue('')
  await expect(projectDialog.getByLabel('描述')).toHaveValue('')
  await projectDialog.getByRole('button', { name: '关闭' }).click()

  await page.goto('/instances')
  await expect(page.getByText('尚未创建数据库。接入可用主机后，即可从目录选择模板部署。')).toBeVisible()
  await expect(page.locator('.page-header').getByRole('button', { name: '接入主机' })).toBeVisible()

  await page.goto('/images')
  await expect(page.getByText('尚未上传离线镜像。上传 docker save 导出的镜像包，即可在无法访问镜像仓库时部署数据库。')).toBeVisible()
  await expect(page.getByRole('button', { name: '上传离线镜像' }).first()).toBeVisible()

  await page.goto('/catalog')
  await expect(page.locator('.database-icon')).toHaveCount(19)
  await expect(page.getByRole('img', { name: 'MySQL' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'PostgreSQL' })).toBeVisible()
  const cardBaselines = await page.evaluate(() => Array.from(document.querySelectorAll('.template-card')).slice(0, 2).map((card) => {
    const top = (selector: string) => Math.round(card.querySelector(selector)?.getBoundingClientRect().top ?? 0)
    return ['.template-card-title-row', '.template-card-description', '.template-card-tags', '.template-meta', '.ant-card-actions'].map(top)
  }))
  expect(cardBaselines[0]).toEqual(cardBaselines[1])
  await page.getByRole('searchbox', { name: '搜索' }).fill('definitely-no-such-database')
  await expect(page.getByText('没有匹配的数据库模板。请调整搜索词或筛选条件。')).toBeVisible()
  await page.getByRole('button', { name: '清除筛选' }).click()
  await expect(page.locator('.database-icon')).toHaveCount(19)
  await page.locator('.template-card').first().getByRole('button', { name: '创建' }).click()
  const redirectedHostDialog = page.getByRole('dialog', { name: '接入主机' })
  await expect(redirectedHostDialog).toBeVisible()
  await expect(page).toHaveURL(/\/hosts$/)
  await redirectedHostDialog.getByRole('button', { name: '关闭' }).click()

  await page.goto('/audit')
  await page.locator('.page-header').getByRole('button', { name: '清理' }).click()
  let clearAuditDialog = page.getByRole('dialog', { name: '清理' })
  await clearAuditDialog.getByLabel('输入 CLEAR 以确认').fill('CLEAR')
  await expect(clearAuditDialog.getByRole('button', { name: /确\s*定/ })).toBeEnabled()
  await clearAuditDialog.getByRole('button', { name: '关闭' }).click()
  await page.locator('.page-header').getByRole('button', { name: '清理' }).click()
  clearAuditDialog = page.getByRole('dialog', { name: '清理' })
  await expect(clearAuditDialog.getByLabel('输入 CLEAR 以确认')).toHaveValue('')
  await expect(clearAuditDialog.getByRole('button', { name: /确\s*定/ })).toBeDisabled()
  await clearAuditDialog.getByRole('button', { name: '关闭' }).click()
  await page.goto('/')

  await page.getByRole('button', { name: 'English' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'en-US')
  await expect(page.getByText('Dashboard', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Complete your first database deployment', { exact: true })).toBeVisible()
  await expect(page.locator('.page-header').getByRole('button', { name: 'Add host' })).toBeVisible()
  await page.goto('/hosts')
  await expect(page.getByText('Direct SSH only. Linux can optionally install Docker; macOS requires Docker Desktop.')).toBeVisible()

  await page.getByRole('button', { name: '简体中文' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page.getByText('主机', { exact: true }).first()).toBeVisible()
  const health = await page.request.get('/api/v1/health')
  expect(health.ok()).toBeTruthy()
})
