import { BellOutlined, DeleteOutlined, PlusOutlined, SendOutlined } from '@ant-design/icons'
import { App, Button, Card, Col, Form, Input, List, Modal, Popconfirm, Row, Select, Space, Switch, Tabs, Tag, Typography } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { PageHeader, StatusTag } from '../components/Common'
import { api, errorMessage } from '../lib/api'
import type { Alert, Webhook } from '../lib/types'

export function AlertsPage() {
  const { t } = useTranslation(); const { message } = App.useApp(); const [alerts, setAlerts] = useState<Alert[]>([]); const [webhooks, setWebhooks] = useState<Webhook[]>([]); const [open, setOpen] = useState(false); const [form] = Form.useForm()
  const load = useCallback(() => Promise.all([api<{ items: Alert[] }>('/alerts'), api<{ items: Webhook[] }>('/webhooks')]).then(([a, w]) => { setAlerts(a.items); setWebhooks(w.items) }).catch((error) => message.error(errorMessage(error))), [message])
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 10000); return () => clearInterval(timer) }, [load])
  const setAlert = async (id: string, status: string) => { try { await api(`/alerts/${id}/${status}`, { method: 'POST', body: {} }); await load() } catch (error) { message.error(errorMessage(error)) } }
  const saveWebhook = async () => { try { const values = await form.validateFields(); await api('/webhooks', { method: 'POST', body: values }); message.success(t('save')); setOpen(false); form.resetFields(); await load() } catch (error) { if (error instanceof Error) message.error(errorMessage(error)) } }
  const webhookAction = async (id: string, action: 'test' | 'delete') => { try { await api(`/webhooks/${id}${action === 'test' ? '/test' : ''}`, { method: action === 'delete' ? 'DELETE' : 'POST', body: action === 'test' ? {} : undefined }); message.success(action === 'test' ? 'Webhook queued' : t('delete')); await load() } catch (error) { message.error(errorMessage(error)) } }
  const alertTab = <Card><List dataSource={alerts} locale={{ emptyText: t('noData') }} renderItem={(item) => <List.Item actions={item.status === 'open' ? [<Button key="ack" onClick={() => void setAlert(item.id, 'acknowledged')}>{t('acknowledge')}</Button>, <Button key="resolve" type="primary" onClick={() => void setAlert(item.id, 'resolved')}>{t('resolve')}</Button>] : item.status === 'acknowledged' ? [<Button key="resolve" type="primary" onClick={() => void setAlert(item.id, 'resolved')}>{t('resolve')}</Button>] : []}><List.Item.Meta avatar={<span className={`alert-icon severity-${item.severity}`}><BellOutlined /></span>} title={<Space>{item.title}<StatusTag value={item.severity} /><StatusTag value={item.status} /></Space>} description={<><Typography.Paragraph>{item.message}</Typography.Paragraph><Typography.Text type="secondary">{item.resourceType} · {item.resourceId.slice(0, 8)} · {new Date(item.createdAt).toLocaleString()}</Typography.Text></>} /></List.Item>} /></Card>
  const webhookTab = <Row gutter={[16, 16]}>{webhooks.map((item) => <Col xs={24} md={12} xl={8} key={item.id}><Card actions={[<SendOutlined key="test" onClick={() => void webhookAction(item.id, 'test')} />, <Popconfirm key="delete" title={t('delete')} onConfirm={() => void webhookAction(item.id, 'delete')}><DeleteOutlined /></Popconfirm>]}><Space direction="vertical" style={{ width: '100%' }}><Space><Typography.Title level={4}>{item.name}</Typography.Title><StatusTag value={item.enabled ? 'online' : 'stopped'} /></Space><Typography.Text copyable ellipsis>{item.url}</Typography.Text><Space wrap>{item.events.map((event) => <Tag key={event}>{event}</Tag>)}</Space>{item.hasSecret && <Typography.Text type="secondary">HMAC signing enabled</Typography.Text>}</Space></Card></Col>)}{webhooks.length === 0 && <Col span={24}><Card><Typography.Text type="secondary">No webhooks configured.</Typography.Text></Card></Col>}</Row>
  return <><PageHeader title={t('alerts')} description="Resource alerts with signed generic webhook delivery and five retries." actions={<Button type="primary" icon={<PlusOutlined />} onClick={() => { form.setFieldsValue({ enabled: true, events: ['alert.created'] }); setOpen(true) }}>{t('webhook')}</Button>} /><Tabs items={[{ key: 'alerts', label: t('alerts'), children: alertTab },{ key: 'webhooks', label: t('webhook'), children: webhookTab }]} />
    <Modal title={t('webhook')} open={open} onCancel={() => setOpen(false)} onOk={() => void saveWebhook()}><Form form={form} layout="vertical"><Form.Item name="name" label={t('name')} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="url" label="URL" rules={[{ required: true }, { type: 'url' }]}><Input placeholder="https://example.com/hooks/dbmock" /></Form.Item><Form.Item name="secret" label="HMAC secret"><Input.Password /></Form.Item><Form.Item name="events" label="Events"><Select mode="tags" options={['*', 'alert.created', 'instance.failed', 'instance.restart_failed', 'host.offline', 'host.disk_warning', 'host.disk_critical', 'task.finished', 'task.succeeded', 'task.failed', 'webhook.test'].map((value) => ({ value }))} /></Form.Item><Form.Item name="enabled" label="Enabled" valuePropName="checked"><Switch /></Form.Item></Form></Modal>
  </>
}
