import { CloudUploadOutlined, DeleteOutlined, PlusOutlined, SafetyCertificateOutlined } from '@ant-design/icons'
import { App, Button, Card, Col, Form, Input, Modal, Popconfirm, Progress, Row, Space, Table, Tabs, Tag, Typography, Upload } from 'antd'
import type { UploadFile } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { EmptyState, PageHeader, StatusTag } from '../components/Common'
import { api, errorMessage, uploadInChunks } from '../lib/api'
import type { ImageArtifact, Registry } from '../lib/types'
import { bytes } from '../lib/types'

export function ImagesPage() {
  const { t } = useTranslation(); const { message } = App.useApp(); const [images, setImages] = useState<ImageArtifact[]>([]); const [registries, setRegistries] = useState<Registry[]>([]); const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [savingRegistry, setSavingRegistry] = useState(false); const [imageOpen, setImageOpen] = useState(false); const [registryOpen, setRegistryOpen] = useState(false); const [file, setFile] = useState<UploadFile | null>(null); const [progress, setProgress] = useState(0); const [form] = Form.useForm()
  const load = useCallback(() => Promise.all([api<{ items: ImageArtifact[] }>('/images'), api<{ items: Registry[] }>('/registries')]).then(([a, r]) => { setImages(a.items); setRegistries(r.items) }).catch((e) => message.error(errorMessage(e))).finally(() => setLoading(false)), [message]); useEffect(() => { void load() }, [load])
  const showImageUpload = () => { setFile(null); setProgress(0); setImageOpen(true) }
  const showRegistry = () => { form.resetFields(); setRegistryOpen(true) }
  const upload = async () => { if (!file?.originFileObj) return; try { setUploading(true); await uploadInChunks(file.originFileObj, setProgress); message.success(t('uploadImage')); setImageOpen(false); setFile(null); setProgress(0); await load() } catch (e) { message.error(errorMessage(e)) } finally { setUploading(false) } }
  const saveRegistry = async () => { try { setSavingRegistry(true); const values = await form.validateFields(); await api('/registries', { method: 'POST', body: values }); message.success(t('saved')); setRegistryOpen(false); form.resetFields(); await load() } catch (e) { if (e instanceof Error) message.error(errorMessage(e)) } finally { setSavingRegistry(false) } }
  const removeImage = async (id: string) => { try { await api(`/images/${id}`, { method: 'DELETE' }); await load() } catch (e) { message.error(errorMessage(e)) } }
  const removeRegistry = async (id: string) => { try { await api(`/registries/${id}`, { method: 'DELETE' }); await load() } catch (e) { message.error(errorMessage(e)) } }
  const imageTab = <Card><Table rowKey="id" loading={loading} dataSource={images} pagination={false} locale={{ emptyText: <EmptyState compact action={showImageUpload} actionLabel={t('uploadImage')} description={t('imagesEmptyDescription')} /> }} columns={[{ title: t('name'), dataIndex: 'name' },{ title: t('imageReferences'), dataIndex: 'imageRefs', render: (values: string[]) => <Space wrap>{values?.map((v) => <Tag key={v}>{v}</Tag>)}</Space> },{ title: t('architecture'), dataIndex: 'architectures', render: (values: string[]) => values?.join(', ') || t('unknown') },{ title: t('size'), dataIndex: 'sizeBytes', render: bytes },{ title: t('sha256'), dataIndex: 'sha256', render: (v: string) => <Typography.Text code copyable>{v.slice(0, 16)}…</Typography.Text> },{ title: t('status'), dataIndex: 'status', render: (v: string) => <StatusTag value={v} /> },{ title: '', render: (_: unknown, item: ImageArtifact) => <Popconfirm title={t('delete')} onConfirm={() => void removeImage(item.id)}><Button danger type="text" aria-label={`${t('delete')} ${item.name}`} title={t('delete')} icon={<DeleteOutlined />} /></Popconfirm> }]} /></Card>
  const registryTab = loading ? <Card loading /> : <Row gutter={[16, 16]}>{registries.map((item) => <Col xs={24} md={12} xl={8} key={item.id}><Card actions={[<Popconfirm key="delete" title={t('delete')} onConfirm={() => void removeRegistry(item.id)}><Button type="text" danger aria-label={`${t('delete')} ${item.name}`} title={t('delete')} icon={<DeleteOutlined />} /></Popconfirm>]}><Space direction="vertical"><Space><span className="template-avatar"><SafetyCertificateOutlined /></span><Typography.Title level={4}>{item.name}</Typography.Title></Space><Typography.Text copyable>{item.url}</Typography.Text><Space>{item.hasPassword && <Tag>{t('credentials')}</Tag>}{item.hasCaCertificate && <Tag color="cyan">{t('customCA')}</Tag>}</Space></Space></Card></Col>)}{registries.length === 0 && <Col span={24}><Card><EmptyState action={showRegistry} actionLabel={t('registry')} description={t('registriesEmptyDescription')} /></Card></Col>}</Row>
  return <><PageHeader title={t('images')} description={t('imagesDescription')} actions={<Space><Button icon={<PlusOutlined />} onClick={showRegistry}>{t('registry')}</Button><Button type="primary" icon={<CloudUploadOutlined />} onClick={showImageUpload}>{t('uploadImage')}</Button></Space>} /><Tabs items={[{ key: 'images', label: t('uploadImage'), children: imageTab }, { key: 'registries', label: t('registry'), children: registryTab }]} />
    <Modal title={t('uploadImage')} open={imageOpen} onCancel={() => { if (!uploading) setImageOpen(false) }} onOk={() => void upload()} confirmLoading={uploading} okText={t('uploadImage')} okButtonProps={{ disabled: !file }} width={640}><Typography.Paragraph type="secondary">{t('imageUploadHint')}</Typography.Paragraph><Upload.Dragger accept=".tar,.gz,.tgz" maxCount={1} beforeUpload={() => false} fileList={file ? [file] : []} disabled={uploading} onChange={({ fileList }) => setFile(fileList.at(-1) ?? null)}><p className="ant-upload-drag-icon"><CloudUploadOutlined /></p><p>{t('dropImageArchive')}</p></Upload.Dragger>{progress > 0 && <Progress percent={progress} style={{ marginTop: 20 }} />}</Modal>
    <Modal title={t('registry')} open={registryOpen} onCancel={() => setRegistryOpen(false)} onOk={() => void saveRegistry()} confirmLoading={savingRegistry} okText={t('save')}><Form form={form} layout="vertical" autoComplete="off"><Form.Item name="name" label={t('name')} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="url" label={t('registryURL')} rules={[{ required: true }]}><Input type="url" placeholder={t('registryURLPlaceholder')} /></Form.Item><Form.Item name="username" label={t('username')}><Input autoComplete="off" data-1p-ignore data-lpignore="true" /></Form.Item><Form.Item name="password" label={t('password')}><Input.Password autoComplete="new-password" data-1p-ignore data-lpignore="true" /></Form.Item><Form.Item name="caCertificate" label={t('selfSignedCA')}><Input.TextArea rows={5} placeholder={t('certificatePlaceholder')} /></Form.Item></Form></Modal>
  </>
}
