import { CloudUploadOutlined, DeleteOutlined, PlusOutlined, SafetyCertificateOutlined } from '@ant-design/icons'
import { App, Button, Card, Col, Form, Input, Modal, Popconfirm, Progress, Row, Space, Table, Tabs, Tag, Typography, Upload } from 'antd'
import type { UploadFile } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { PageHeader, StatusTag } from '../components/Common'
import { api, errorMessage, uploadInChunks } from '../lib/api'
import type { ImageArtifact, Registry } from '../lib/types'
import { bytes } from '../lib/types'

export function ImagesPage() {
  const { t } = useTranslation(); const { message } = App.useApp(); const [images, setImages] = useState<ImageArtifact[]>([]); const [registries, setRegistries] = useState<Registry[]>([]); const [imageOpen, setImageOpen] = useState(false); const [registryOpen, setRegistryOpen] = useState(false); const [file, setFile] = useState<UploadFile | null>(null); const [progress, setProgress] = useState(0); const [form] = Form.useForm()
  const load = useCallback(() => Promise.all([api<{ items: ImageArtifact[] }>('/images'), api<{ items: Registry[] }>('/registries')]).then(([a, r]) => { setImages(a.items); setRegistries(r.items) }).catch((e) => message.error(errorMessage(e))), [message]); useEffect(() => { void load() }, [load])
  const upload = async () => { if (!file?.originFileObj) return; try { await uploadInChunks(file.originFileObj, setProgress); message.success(t('uploadImage')); setImageOpen(false); setFile(null); setProgress(0); await load() } catch (e) { message.error(errorMessage(e)) } }
  const saveRegistry = async () => { try { const values = await form.validateFields(); await api('/registries', { method: 'POST', body: values }); message.success(t('save')); setRegistryOpen(false); form.resetFields(); await load() } catch (e) { if (e instanceof Error) message.error(errorMessage(e)) } }
  const removeImage = async (id: string) => { try { await api(`/images/${id}`, { method: 'DELETE' }); await load() } catch (e) { message.error(errorMessage(e)) } }
  const removeRegistry = async (id: string) => { try { await api(`/registries/${id}`, { method: 'DELETE' }); await load() } catch (e) { message.error(errorMessage(e)) } }
  const imageTab = <Card><Table rowKey="id" dataSource={images} pagination={false} columns={[{ title: t('name'), dataIndex: 'name' },{ title: 'Image references', dataIndex: 'imageRefs', render: (values: string[]) => <Space wrap>{values?.map((v) => <Tag key={v}>{v}</Tag>)}</Space> },{ title: 'Architecture', dataIndex: 'architectures', render: (values: string[]) => values?.join(', ') || 'unknown' },{ title: 'Size', dataIndex: 'sizeBytes', render: bytes },{ title: 'SHA-256', dataIndex: 'sha256', render: (v: string) => <Typography.Text code copyable>{v.slice(0, 16)}…</Typography.Text> },{ title: t('status'), dataIndex: 'status', render: (v: string) => <StatusTag value={v} /> },{ title: '', render: (_: unknown, item: ImageArtifact) => <Popconfirm title={t('delete')} onConfirm={() => void removeImage(item.id)}><Button danger type="text" icon={<DeleteOutlined />} /></Popconfirm> }]} /></Card>
  const registryTab = <Row gutter={[16, 16]}>{registries.map((item) => <Col xs={24} md={12} xl={8} key={item.id}><Card actions={[<Popconfirm key="delete" title={t('delete')} onConfirm={() => void removeRegistry(item.id)}><DeleteOutlined /></Popconfirm>]}><Space direction="vertical"><Space><span className="template-avatar"><SafetyCertificateOutlined /></span><Typography.Title level={4}>{item.name}</Typography.Title></Space><Typography.Text copyable>{item.url}</Typography.Text><Space>{item.hasPassword && <Tag>Credentials</Tag>}{item.hasCaCertificate && <Tag color="cyan">Custom CA</Tag>}</Space></Space></Card></Col>)}</Row>
  return <><PageHeader title={t('images')} description="Resumable Docker save archives and authenticated OCI registries." actions={<Space><Button icon={<PlusOutlined />} onClick={() => setRegistryOpen(true)}>{t('registry')}</Button><Button type="primary" icon={<CloudUploadOutlined />} onClick={() => setImageOpen(true)}>{t('uploadImage')}</Button></Space>} /><Tabs items={[{ key: 'images', label: t('uploadImage'), children: imageTab }, { key: 'registries', label: t('registry'), children: registryTab }]} />
    <Modal title={t('uploadImage')} open={imageOpen} onCancel={() => setImageOpen(false)} onOk={() => void upload()} okButtonProps={{ disabled: !file || progress > 0 }} width={640}><Typography.Paragraph type="secondary">Accepts docker save .tar, .tar.gz or .tgz up to the configured 50 GiB limit.</Typography.Paragraph><Upload.Dragger accept=".tar,.gz,.tgz" maxCount={1} beforeUpload={() => false} fileList={file ? [file] : []} onChange={({ fileList }) => setFile(fileList.at(-1) ?? null)}><p className="ant-upload-drag-icon"><CloudUploadOutlined /></p><p>Choose or drop a Docker image archive</p></Upload.Dragger>{progress > 0 && <Progress percent={progress} style={{ marginTop: 20 }} />}</Modal>
    <Modal title={t('registry')} open={registryOpen} onCancel={() => setRegistryOpen(false)} onOk={() => void saveRegistry()}><Form form={form} layout="vertical"><Form.Item name="name" label={t('name')} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="url" label="Registry URL" rules={[{ required: true }]}><Input placeholder="https://harbor.example.com" /></Form.Item><Form.Item name="username" label={t('username')}><Input /></Form.Item><Form.Item name="password" label={t('password')}><Input.Password /></Form.Item><Form.Item name="caCertificate" label="Self-signed CA certificate"><Input.TextArea rows={5} placeholder="-----BEGIN CERTIFICATE-----" /></Form.Item></Form></Modal>
  </>
}
