import { CopyOutlined, DeleteOutlined, EditOutlined, MoreOutlined, PauseCircleOutlined, PlayCircleOutlined, PlusOutlined, ReloadOutlined, RocketOutlined, SyncOutlined } from '@ant-design/icons'
import { App, Button, Card, Col, Descriptions, Drawer, Form, Input, InputNumber, Modal, Popconfirm, Progress, Row, Select, Space, Steps, Switch, Table, Tabs, Tag, Typography } from 'antd'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { PageHeader, StatusTag } from '../components/Common'
import { api, errorMessage } from '../lib/api'
import type { DatabaseTemplate, Host, ImageArtifact, Instance, Project, Registry, Task, TemplateVersion } from '../lib/types'
import { bytes } from '../lib/types'

interface CreateValues { name: string; projectId?: string; environment: string; templateVersionId: string; hostId?: string; cpu: number; memoryGiB: number; diskGiB: number; hostPort?: number; bindAddress: string; username?: string; password?: string; databaseName?: string; autoRestart: boolean; imageArtifactId?: string; registryId?: string; labels?: string; extraEnvironment?: string }

export function InstancesPage() {
  const { t } = useTranslation(); const { message } = App.useApp(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const [items, setItems] = useState<Instance[]>([]); const [templates, setTemplates] = useState<DatabaseTemplate[]>([]); const [hosts, setHosts] = useState<Host[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [images, setImages] = useState<ImageArtifact[]>([]); const [registries, setRegistries] = useState<Registry[]>([]); const [drawer, setDrawer] = useState(false); const [step, setStep] = useState(0); const [search, setSearch] = useState(''); const [projectFilter, setProjectFilter] = useState(''); const [environmentFilter, setEnvironmentFilter] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [form] = Form.useForm<CreateValues>()
  const load = useCallback(() => Promise.all([api<{ items: Instance[] }>('/instances'), api<{ items: DatabaseTemplate[] }>('/templates'), api<{ items: Host[] }>('/hosts'), api<{ items: Project[] }>('/projects'), api<{ items: ImageArtifact[] }>('/images'), api<{ items: Registry[] }>('/registries')]).then(([i, tpls, h, p, im, r]) => { setItems(i.items); setTemplates(tpls.items); setHosts(h.items); setProjects(p.items); setImages(im.items); setRegistries(r.items) }).catch((e) => message.error(errorMessage(e))), [message])
  useEffect(() => { void load() }, [load]); useEffect(() => { if (params.get('create') === '1') { setDrawer(true); const version = params.get('template'); if (version) form.setFieldValue('templateVersionId', version) } }, [params, form])
  const selectedVersionID = Form.useWatch('templateVersionId', form); const selected = useMemo(() => { for (const item of templates) for (const version of item.versions) if (version.id === selectedVersionID) return { template: item, version }; return undefined }, [templates, selectedVersionID])
  useEffect(() => { if (!selected) return; const manifest = selected.version.manifest as { username?: string; database?: string }; form.setFieldsValue({ cpu: selected.version.minCpu, memoryGiB: selected.version.minMemoryBytes / 1024 ** 3, diskGiB: selected.version.minDiskBytes / 1024 ** 3, username: manifest.username, databaseName: manifest.database }) }, [selected, form])
  const openCreate = () => { setDrawer(true); setStep(0); form.resetFields(); form.setFieldsValue({ environment: 'development', bindAddress: '0.0.0.0', autoRestart: true }) }
  const close = () => { setDrawer(false); setParams({}); setStep(0) }
  const next = async () => { const fields = step === 0 ? ['templateVersionId'] : step === 1 ? ['name', 'environment'] : step === 2 ? ['cpu', 'memoryGiB', 'diskGiB', 'bindAddress'] : []; try { await form.validateFields(fields); setStep(Math.min(step + 1, 4)) } catch { /* form marks errors */ } }
  const create = async () => { try { const values = await form.validateFields(); const labels: Record<string, string> = {}; values.labels?.split(',').forEach((part) => { const [key, value] = part.split('='); if (key?.trim()) labels[key.trim()] = value?.trim() || 'true' }); let extraEnvironment: Record<string, string> = {}; if (values.extraEnvironment?.trim()) extraEnvironment = JSON.parse(values.extraEnvironment); const payload = { name: values.name, projectId: values.projectId || null, environment: values.environment, templateVersionId: values.templateVersionId, hostId: values.hostId || null, cpu: values.cpu, memoryBytes: Math.round(values.memoryGiB * 1024 ** 3), diskBytes: Math.round(values.diskGiB * 1024 ** 3), hostPort: values.hostPort || 0, bindAddress: values.bindAddress, username: values.username || '', password: values.password || '', databaseName: values.databaseName || '', autoRestart: values.autoRestart, imageArtifactId: values.imageArtifactId || null, registryId: values.registryId || null, labels, extraEnvironment }; const result = await api<{ instance: Instance; task: Task }>('/instances', { method: 'POST', body: payload }); message.success(`${t('tasks')}: ${result.task.id.slice(0, 8)}`); close(); navigate(`/instances/${result.instance.id}`) } catch (e) { if (e instanceof Error) message.error(errorMessage(e)) } }
  const quickAction = async (item: Instance, action: string) => { try { await api(`/instances/${item.id}/actions/${action}`, { method: 'POST', body: {} }); message.success(t('tasks')); await load() } catch (e) { message.error(errorMessage(e)) } }
  const columns = [
    { title: t('name'), dataIndex: 'name', render: (value: string, item: Instance) => <Button type="link" onClick={() => navigate(`/instances/${item.id}`)}>{value}</Button> },
    { title: t('template'), render: (_: unknown, item: Instance) => <Space><span className="template-avatar">{item.templateSlug.slice(0, 2).toUpperCase()}</span><span>{item.templateName} <Typography.Text type="secondary">{item.templateVersion}</Typography.Text></span></Space> },
    { title: t('status'), dataIndex: 'status', render: (value: string) => <StatusTag value={value} /> },
    { title: t('host'), render: (_: unknown, item: Instance) => <><Typography.Text>{item.hostName}</Typography.Text><br /><Typography.Text type="secondary">{item.connectionAddress}:{item.hostPort}</Typography.Text></> },
    { title: t('resources'), render: (_: unknown, item: Instance) => `${item.cpu} CPU · ${bytes(item.memoryBytes)} · ${bytes(item.reservedDiskBytes)}` },
    { title: t('environment'), dataIndex: 'environment', render: (value: string) => <Tag>{value}</Tag> },
    { title: '', align: 'right' as const, render: (_: unknown, item: Instance) => <Space><Button type="text" icon={item.status === 'running' ? <PauseCircleOutlined /> : <PlayCircleOutlined />} onClick={() => void quickAction(item, item.status === 'running' ? 'stop' : 'start')} /><Button type="text" icon={<MoreOutlined />} onClick={() => navigate(`/instances/${item.id}`)} /></Space> },
  ]
  const versionOptions = templates.flatMap((item) => item.versions.map((version) => ({ value: version.id, label: `${item.name} ${version.version}`, template: item, version })))
  const filteredItems = useMemo(() => items.filter((item) => (!projectFilter || item.projectId === projectFilter) && (!environmentFilter || item.environment === environmentFilter) && (!statusFilter || item.status === statusFilter) && `${item.name} ${item.templateName} ${item.hostName} ${JSON.stringify(item.labels)}`.toLowerCase().includes(search.toLowerCase())), [items, projectFilter, environmentFilter, statusFilter, search])
  return <><PageHeader title={t('instances')} description="Single-host Docker Compose database instances." actions={<><Button icon={<ReloadOutlined />} onClick={() => void load()}>{t('refresh')}</Button><Button type="primary" icon={<PlusOutlined />} onClick={openCreate}>{t('createInstance')}</Button></>} />
    <Card className="table-filter-card"><Space wrap><Input.Search allowClear placeholder={t('search')} onChange={(event) => setSearch(event.target.value)} style={{ width: 240 }} /><Select value={projectFilter} onChange={setProjectFilter} style={{ width: 170 }} options={[{ value: '', label: `All ${t('projects')}` }, ...projects.map((project) => ({ value: project.id, label: project.name }))]} /><Select value={environmentFilter} onChange={setEnvironmentFilter} style={{ width: 160 }} options={[{ value: '', label: `All ${t('environment')}` }, ...['development', 'testing', 'staging', 'production'].map((value) => ({ value, label: value }))]} /><Select value={statusFilter} onChange={setStatusFilter} style={{ width: 150 }} options={[{ value: '', label: `All ${t('status')}` }, ...['provisioning', 'running', 'stopped', 'degraded', 'failed'].map((value) => ({ value, label: value }))]} /></Space></Card><Card><Table rowKey="id" dataSource={filteredItems} columns={columns} scroll={{ x: 1050 }} /></Card>
    <Drawer title={t('createInstance')} open={drawer} onClose={close} width={720} destroyOnClose extra={<Button type="primary" onClick={step === 4 ? () => void create() : () => void next()}>{step === 4 ? t('create') : 'Next'}</Button>}><Steps current={step} size="small" items={[{ title: t('template') }, { title: t('details') }, { title: t('resources') }, { title: 'Options' }, { title: t('confirm') }]} /><Form form={form} layout="vertical" requiredMark={false} className="wizard-form">
      {step === 0 && <><Form.Item name="templateVersionId" label={`${t('template')} / ${t('version')}`} rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={versionOptions} size="large" /></Form.Item>{selected && <Card><Space align="start"><span className={`template-logo tier-${selected.template.tier}`}>{selected.template.icon}</span><div><Typography.Title level={4}>{selected.template.name}</Typography.Title><Typography.Paragraph type="secondary">{selected.template.description}</Typography.Paragraph><Space><StatusTag value={selected.template.tier} />{selected.version.architectures.map((a) => <Tag key={a}>{a}</Tag>)}</Space></div></Space></Card>}</>}
      {step === 1 && <><Form.Item name="name" label={t('name')} rules={[{ required: true }]}><Input size="large" /></Form.Item><div className="form-grid"><Form.Item name="projectId" label={t('project')}><Select allowClear options={projects.map((p) => ({ value: p.id, label: p.name }))} /></Form.Item><Form.Item name="environment" label={t('environment')} rules={[{ required: true }]}><Select options={['development', 'testing', 'staging', 'production'].map((v) => ({ value: v, label: v }))} /></Form.Item></div><Form.Item name="labels" label="Labels"><Input placeholder="team=data, purpose=test" /></Form.Item><Form.Item name="hostId" label={t('host')} tooltip="Leave empty to automatically recommend a compatible host"><Select allowClear placeholder={t('autoSelect')} options={hosts.filter((h) => h.status === 'online').map((h) => ({ value: h.id, label: `${h.name} · ${h.architecture} · ${h.cpuCount} CPU / ${bytes(h.memoryBytes)}` }))} /></Form.Item></>}
      {step === 2 && <><Row gutter={16}><Col span={8}><Form.Item name="cpu" label={t('cpu')} rules={[{ required: true }]}><InputNumber min={selected?.version.minCpu ?? .25} step={.25} style={{ width: '100%' }} /></Form.Item></Col><Col span={8}><Form.Item name="memoryGiB" label={`${t('memory')} GiB`} rules={[{ required: true }]}><InputNumber min={(selected?.version.minMemoryBytes ?? 0) / 1024 ** 3} step={.5} style={{ width: '100%' }} /></Form.Item></Col><Col span={8}><Form.Item name="diskGiB" label={`${t('disk')} GiB`} rules={[{ required: true }]}><InputNumber min={(selected?.version.minDiskBytes ?? 0) / 1024 ** 3} style={{ width: '100%' }} /></Form.Item></Col></Row><div className="form-grid"><Form.Item name="hostPort" label={`${t('port')} (optional)`}><InputNumber min={1} max={65535} style={{ width: '100%' }} placeholder="Auto allocate" /></Form.Item><Form.Item name="bindAddress" label="Bind address" rules={[{ required: true }]}><Input /></Form.Item></div><Typography.Paragraph type="secondary">Disk is a reservation and alert threshold, not a portable hard quota.</Typography.Paragraph></>}
      {step === 3 && <><div className="form-grid"><Form.Item name="username" label={t('username')}><Input /></Form.Item><Form.Item name="databaseName" label="Database name"><Input /></Form.Item></div><Form.Item name="password" label={t('password')} tooltip="Leave empty to generate a strong password"><Input.Password placeholder="Automatically generated" /></Form.Item><div className="form-grid"><Form.Item name="imageArtifactId" label="Offline image"><Select allowClear options={images.map((i) => ({ value: i.id, label: `${i.name} · ${bytes(i.sizeBytes)}` }))} /></Form.Item><Form.Item name="registryId" label={t('registry')}><Select allowClear options={registries.map((r) => ({ value: r.id, label: r.name }))} /></Form.Item></div><Form.Item name="autoRestart" label={t('autoRestart')} valuePropName="checked"><Switch /></Form.Item><Form.Item name="extraEnvironment" label="Extra environment (JSON)"><Input.TextArea rows={5} placeholder={'{\n  "TZ": "Asia/Shanghai"\n}'} /></Form.Item></>}
      {step === 4 && <Card><Descriptions column={1} items={[{ key: 'template', label: t('template'), children: selected ? `${selected.template.name} ${selected.version.version}` : '—' },{ key: 'name', label: t('name'), children: form.getFieldValue('name') },{ key: 'host', label: t('host'), children: hosts.find((h) => h.id === form.getFieldValue('hostId'))?.name || t('autoSelect') },{ key: 'resources', label: t('resources'), children: `${form.getFieldValue('cpu')} CPU · ${form.getFieldValue('memoryGiB')} GiB · ${form.getFieldValue('diskGiB')} GiB` },{ key: 'port', label: t('port'), children: form.getFieldValue('hostPort') || 'Auto allocate' },{ key: 'restart', label: t('autoRestart'), children: form.getFieldValue('autoRestart') ? 'Enabled' : 'Disabled' }]} /><Typography.Paragraph type="secondary" style={{ marginTop: 20 }}>Creating the instance starts a persistent task. You can safely leave this page and follow progress in the task center.</Typography.Paragraph></Card>}
    </Form></Drawer>
  </>
}

interface Metric { collectedAt: string; cpuPercent: number; memoryBytes: number; memoryPercent: number }
interface Connection { address: string; port: number; username: string; password: string; database: string; uri: string; jdbc?: string }

export function InstanceDetailPage() {
  const { id = '' } = useParams(); const { t } = useTranslation(); const { message } = App.useApp(); const navigate = useNavigate(); const [item, setItem] = useState<Instance | null>(null); const [connection, setConnection] = useState<Connection | null>(null); const [logs, setLogs] = useState(''); const [metrics, setMetrics] = useState<Metric[]>([]); const [templates, setTemplates] = useState<DatabaseTemplate[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [deleteOpen, setDeleteOpen] = useState(false); const [confirm, setConfirm] = useState(''); const [upgradeOpen, setUpgradeOpen] = useState(false); const [upgradeVersion, setUpgradeVersion] = useState<string>(); const [editOpen, setEditOpen] = useState(false); const [activeTab, setActiveTab] = useState('overview'); const [editForm] = Form.useForm()
  const load = useCallback(() => Promise.all([api<Instance>(`/instances/${id}`), api<{ items: DatabaseTemplate[] }>('/templates'), api<{ items: Project[] }>('/projects')]).then(([instance, catalog, projectList]) => { setItem(instance); setTemplates(catalog.items); setProjects(projectList.items) }).catch((e) => message.error(errorMessage(e))), [id, message]); useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 10000); return () => clearInterval(timer) }, [load])
  const run = async (action: string, body: Record<string, unknown> = {}) => { try { await api(`/instances/${id}/actions/${action}`, { method: 'POST', body }); message.success(t('tasks')); setDeleteOpen(false); setUpgradeOpen(false); if (action === 'delete') navigate('/instances'); else await load() } catch (e) { message.error(errorMessage(e)) } }
  const loadConnection = async () => { try { setConnection(await api<Connection>(`/instances/${id}/connection`)) } catch (e) { message.error(errorMessage(e)) } }
  const loadLogs = async () => { try { const response = await fetch(`/api/v1/instances/${id}/logs?tail=1000`, { credentials: 'same-origin' }); if (!response.ok) throw new Error(await response.text()); setLogs(await response.text()) } catch (e) { message.error(errorMessage(e)) } }
  const loadMetrics = async () => { try { const response = await api<{ items: Metric[] }>(`/instances/${id}/metrics?hours=24`); setMetrics(response.items) } catch (e) { message.error(errorMessage(e)) } }
  useEffect(() => { if (activeTab !== 'logs' && activeTab !== 'metrics') return; const refresh = () => activeTab === 'logs' ? loadLogs() : loadMetrics(); void refresh(); const timer = window.setInterval(() => void refresh(), activeTab === 'logs' ? 5000 : 30000); return () => clearInterval(timer) }, [activeTab, id])
  const showEdit = () => { if (!item) return; editForm.setFieldsValue({ name: item.name, projectId: item.projectId, environment: item.environment, labels: Object.entries(item.labels || {}).map(([key, value]) => `${key}=${value}`).join(', '), autoRestart: item.autoRestart }); setEditOpen(true) }
  const saveEdit = async () => { try { const values = await editForm.validateFields(); const labels: Record<string, string> = {}; String(values.labels || '').split(',').forEach((part) => { const [key, value] = part.split('='); if (key?.trim()) labels[key.trim()] = value?.trim() || 'true' }); await api(`/instances/${id}`, { method: 'PATCH', body: { name: values.name, projectId: values.projectId || null, environment: values.environment, labels, autoRestart: !!values.autoRestart } }); message.success(t('save')); setEditOpen(false); await load() } catch (error) { if (error instanceof Error) message.error(errorMessage(error)) } }
  if (!item) return <Card loading />
  const currentTemplate = templates.find((tpl) => tpl.slug === item.templateSlug); const upgradeOptions = currentTemplate?.versions.filter((v) => v.id !== item.templateVersionId).map((v) => ({ value: v.id, label: v.version })) ?? []
  const overview = <Row gutter={[16, 16]}><Col xs={24} lg={16}><Card title="Runtime"><Descriptions column={2} items={[{ key: 'status', label: t('status'), children: <StatusTag value={item.status} /> },{ key: 'desired', label: 'Desired state', children: item.desiredState },{ key: 'template', label: t('template'), children: `${item.templateName} ${item.templateVersion}` },{ key: 'host', label: t('host'), children: item.hostName },{ key: 'resource', label: t('resources'), children: `${item.cpu} CPU · ${bytes(item.memoryBytes)} · ${bytes(item.reservedDiskBytes)}` },{ key: 'port', label: t('port'), children: `${item.bindAddress}:${item.hostPort} → ${item.containerPort}` },{ key: 'env', label: t('environment'), children: <Tag>{item.environment}</Tag> },{ key: 'restart', label: t('autoRestart'), children: item.autoRestart ? 'Enabled' : 'Disabled' }]} /></Card></Col><Col xs={24} lg={8}><Card title="Health"><Progress type="dashboard" percent={item.status === 'running' ? 100 : item.status === 'degraded' ? 50 : 0} status={item.status === 'failed' ? 'exception' : 'normal'} /><Typography.Paragraph type="secondary">{item.statusMessage || 'No active health issue.'}</Typography.Paragraph></Card></Col></Row>
  const connectionTab = <Card><Button type="primary" onClick={() => void loadConnection()}>{connection ? t('refresh') : t('connection')}</Button>{connection && <Descriptions column={1} className="secret-details" items={Object.entries(connection).filter(([, value]) => value).map(([key, value]) => ({ key, label: key, children: <Typography.Text code copyable={{ icon: <CopyOutlined /> }}>{String(value)}</Typography.Text> }))} />}</Card>
  const logsTab = <Card extra={<Space><Button icon={<ReloadOutlined />} onClick={() => void loadLogs()}>{t('refresh')}</Button><Button href={`/api/v1/instances/${id}/logs?tail=10000&download=true`}>Download</Button></Space>} title={t('logs')}><pre className="log-viewer">{logs || 'Load logs to begin.'}</pre></Card>
  const metricsTab = <Card title={t('metrics')} extra={<Button icon={<ReloadOutlined />} onClick={() => void loadMetrics()}>{t('refresh')}</Button>}><div style={{ height: 360 }}><ResponsiveContainer width="100%" height="100%"><LineChart data={metrics.map((m) => ({ ...m, time: new Date(m.collectedAt).toLocaleTimeString(), memoryMiB: Math.round(m.memoryBytes / 1024 ** 2) }))}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="time" minTickGap={40} /><YAxis yAxisId="left" /><YAxis yAxisId="right" orientation="right" /><Tooltip /><Legend /><Line yAxisId="left" type="monotone" dataKey="cpuPercent" name="CPU %" stroke="#2563eb" dot={false} /><Line yAxisId="right" type="monotone" dataKey="memoryMiB" name="Memory MiB" stroke="#13a8a8" dot={false} /></LineChart></ResponsiveContainer></div></Card>
  return <><PageHeader title={<Space><Button type="text" onClick={() => navigate('/instances')}>←</Button>{item.name}<StatusTag value={item.status} /></Space>} description={`${item.templateName} ${item.templateVersion} · ${item.hostName}`} actions={<><Button icon={<EditOutlined />} onClick={showEdit}>{t('edit')}</Button><Button icon={<PlayCircleOutlined />} disabled={item.status === 'running'} onClick={() => void run('start')}>{t('start')}</Button><Button icon={<PauseCircleOutlined />} disabled={item.status === 'stopped'} onClick={() => void run('stop')}>{t('stop')}</Button><Button icon={<ReloadOutlined />} onClick={() => void run('restart')}>{t('restart')}</Button><Button icon={<RocketOutlined />} onClick={() => setUpgradeOpen(true)}>{t('upgrade')}</Button><Button danger icon={<DeleteOutlined />} onClick={() => setDeleteOpen(true)}>{t('delete')}</Button></>} /><Tabs activeKey={activeTab} onChange={setActiveTab} items={[{ key: 'overview', label: t('details'), children: overview },{ key: 'connection', label: t('connection'), children: connectionTab },{ key: 'logs', label: t('logs'), children: logsTab },{ key: 'metrics', label: t('metrics'), children: metricsTab }]} />
    <Modal title={t('edit')} open={editOpen} onCancel={() => setEditOpen(false)} onOk={() => void saveEdit()}><Form form={editForm} layout="vertical"><Form.Item name="name" label={t('name')} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="projectId" label={t('project')}><Select allowClear options={projects.map((project) => ({ value: project.id, label: project.name }))} /></Form.Item><Form.Item name="environment" label={t('environment')} rules={[{ required: true }]}><Select options={['development', 'testing', 'staging', 'production'].map((value) => ({ value, label: value }))} /></Form.Item><Form.Item name="labels" label="Labels"><Input placeholder="team=data, purpose=test" /></Form.Item><Form.Item name="autoRestart" label={t('autoRestart')} valuePropName="checked"><Switch /></Form.Item></Form></Modal>
    <Modal title={`${t('delete')} ${item.name}`} open={deleteOpen} onCancel={() => setDeleteOpen(false)} onOk={() => void run('delete', { confirmName: confirm })} okButtonProps={{ danger: true, disabled: confirm !== item.name }}><Typography.Paragraph>{t('dangerConfirm')}</Typography.Paragraph><Input value={confirm} onChange={(e) => setConfirm(e.target.value)} placeholder={item.name} /></Modal>
    <Modal title={t('upgrade')} open={upgradeOpen} onCancel={() => setUpgradeOpen(false)} onOk={() => upgradeVersion && void run('upgrade', { templateVersionId: upgradeVersion })} okButtonProps={{ disabled: !upgradeVersion }}><Typography.Paragraph type="secondary">Same-major upgrades stop the instance, create a short-lived internal snapshot, verify health, and remove the snapshot after success.</Typography.Paragraph><Select style={{ width: '100%' }} options={upgradeOptions} value={upgradeVersion} onChange={setUpgradeVersion} placeholder={t('version')} />{upgradeOptions.length === 0 && <Typography.Text type="warning">No compatible additional version is installed in the catalog.</Typography.Text>}</Modal>
  </>
}
