import { CloseCircleOutlined, ReloadOutlined, RedoOutlined } from '@ant-design/icons'
import { App, Button, Card, Drawer, Progress, Select, Space, Table, Tag, Timeline, Typography } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { PageHeader, StatusTag } from '../components/Common'
import { api, errorMessage } from '../lib/api'
import { formatDateTime, translateCode } from '../lib/localization'
import type { Task } from '../lib/types'

interface TaskLog { id: number; level: string; message: string; createdAt: string }

export function TasksPage() {
  const { t, i18n } = useTranslation(); const { message } = App.useApp(); const [items, setItems] = useState<Task[]>([]); const [status, setStatus] = useState(''); const [selected, setSelected] = useState<Task | null>(null); const [logs, setLogs] = useState<TaskLog[]>([])
  const load = useCallback(() => api<{ items: Task[] }>(`/tasks${status ? `?status=${status}` : ''}`).then((value) => setItems(value.items)).catch((error) => message.error(errorMessage(error))), [message, status])
  const loadDetail = useCallback(async (item: Task) => { try { const [task, result] = await Promise.all([api<Task>(`/tasks/${item.id}`), api<{ items: TaskLog[] }>(`/tasks/${item.id}/logs`)]); setSelected(task); setLogs(result.items) } catch (error) { message.error(errorMessage(error)) } }, [message])
  useEffect(() => { void load(); const timer = window.setInterval(() => { void load(); if (selected) void loadDetail(selected) }, 3000); return () => clearInterval(timer) }, [load, loadDetail, selected])
  const action = async (item: Task, name: 'cancel' | 'retry') => { try { await api(`/tasks/${item.id}/${name}`, { method: 'POST', body: {} }); message.success(t('tasks')); await load() } catch (error) { message.error(errorMessage(error)) } }
  return <><PageHeader title={t('tasks')} description={t('tasksDescription')} actions={<Space><Select value={status} onChange={setStatus} style={{ width: 150 }} options={[{ value: '', label: t('taskStatusAll') }, ...['queued', 'running', 'succeeded', 'failed', 'canceled'].map((value) => ({ value, label: translateCode(t, value) }))]} /><Button icon={<ReloadOutlined />} onClick={() => void load()}>{t('refresh')}</Button></Space>} />
    <Card><Table rowKey="id" dataSource={items} scroll={{ x: 920 }} columns={[{ title: t('status'), dataIndex: 'status', render: (value: string) => <StatusTag value={value} /> },{ title: t('operation'), render: (_: unknown, item: Task) => <Button type="link" onClick={() => void loadDetail(item)}>{translateCode(t, item.kind, 'taskKind')}</Button> },{ title: t('resources'), render: (_: unknown, item: Task) => <><Tag>{translateCode(t, item.resourceType, 'resourceType')}</Tag>{item.resourceId?.slice(0, 8) || '—'}</> },{ title: t('progress'), width: 210, render: (_: unknown, item: Task) => <Progress percent={item.progress} status={item.status === 'failed' ? 'exception' : undefined} size="small" /> },{ title: t('stage'), render: (_: unknown, item: Task) => <><Typography.Text>{translateCode(t, item.stage)}</Typography.Text><br /><Typography.Text type="secondary">{item.errorMessage || translateCode(t, item.message, 'taskMessage')}</Typography.Text></> },{ title: t('createdAt'), dataIndex: 'createdAt', render: (value: string) => formatDateTime(value, i18n.language) },{ title: '', render: (_: unknown, item: Task) => <Space><Button type="text" title={t('retry')} icon={<RedoOutlined />} disabled={item.status !== 'failed' && item.status !== 'canceled'} onClick={() => void action(item, 'retry')} /><Button type="text" danger title={t('taskCanceled')} icon={<CloseCircleOutlined />} disabled={!item.cancelable || !['queued', 'running'].includes(item.status)} onClick={() => void action(item, 'cancel')} /></Space> }]} /></Card>
    <Drawer title={selected ? `${translateCode(t, selected.kind, 'taskKind')} · ${selected.id.slice(0, 8)}` : t('details')} open={!!selected} onClose={() => setSelected(null)} width={680}><Space direction="vertical" size="large" style={{ width: '100%' }}><Space><StatusTag value={selected?.status || 'pending'} /><Typography.Text>{selected && translateCode(t, selected.message, 'taskMessage')}</Typography.Text></Space><Progress percent={selected?.progress || 0} status={selected?.status === 'failed' ? 'exception' : undefined} /><Timeline items={logs.map((log) => ({ color: log.level === 'error' ? 'red' : log.level === 'warning' ? 'orange' : 'blue', children: <><Typography.Text type="secondary">{formatDateTime(log.createdAt, i18n.language)}</Typography.Text><br /><Typography.Text>{translateCode(t, log.message, 'taskMessage')}</Typography.Text></> }))} />{selected?.errorMessage && <Typography.Paragraph type="danger" copyable>{selected.errorMessage}</Typography.Paragraph>}</Space></Drawer>
  </>
}
