import { EditOutlined, PlusOutlined } from '@ant-design/icons'
import { App, Button, Card, Form, Input, Modal, Select, Space, Switch, Table, Tag, Typography } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { PageHeader } from '../components/Common'
import { useAuth } from '../contexts/AuthContext'
import { api, errorMessage } from '../lib/api'
import { formatDateTime } from '../lib/localization'
import type { User } from '../lib/types'

interface UserForm { username?: string; displayName: string; password?: string; locale: string; disabled?: boolean }

export function UsersPage() {
  const { t, i18n } = useTranslation(); const { message } = App.useApp(); const { user: currentUser, reload: reloadCurrentUser } = useAuth(); const [items, setItems] = useState<User[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<User | null>(null); const [form] = Form.useForm<UserForm>()
  const load = useCallback(() => api<{ items: User[] }>('/users').then((value) => setItems(value.items)).catch((error) => message.error(errorMessage(error))).finally(() => setLoading(false)), [message])
  useEffect(() => { void load() }, [load])
  const show = (item?: User) => { setEditing(item || null); form.resetFields(); form.setFieldsValue(item ? { displayName: item.displayName, locale: item.locale, disabled: !!item.disabledAt } : { locale: i18n.language, disabled: false }); setOpen(true) }
  const save = async () => { try { setSaving(true); const values = await form.validateFields(); const body = editing ? { displayName: values.displayName, locale: values.locale, password: values.password || '', disabled: !!values.disabled } : { username: values.username, displayName: values.displayName, locale: values.locale, password: values.password }; await api(editing ? `/users/${editing.id}` : '/users', { method: editing ? 'PATCH' : 'POST', body }); if (editing?.id === currentUser?.id) await reloadCurrentUser(); message.success(t('saved')); setOpen(false); await load() } catch (error) { if (error instanceof Error) message.error(errorMessage(error)) } finally { setSaving(false) } }
  return <><PageHeader title={t('users')} description={t('usersDescription')} actions={<Button type="primary" icon={<PlusOutlined />} onClick={() => show()}>{t('create')}</Button>} /><Card><Table rowKey="id" loading={loading} dataSource={items} pagination={false} columns={[{ title: t('username'), dataIndex: 'username', render: (value: string, item: User) => <Space><span className="user-avatar">{item.displayName.slice(0, 1).toUpperCase()}</span><div><Typography.Text strong>{item.displayName}</Typography.Text><br /><Typography.Text type="secondary">{value}</Typography.Text></div></Space> },{ title: t('language'), dataIndex: 'locale', render: (value: string) => <Tag>{value === 'zh-CN' ? t('languageChinese') : t('languageEnglish')}</Tag> },{ title: t('status'), render: (_: unknown, item: User) => <Tag color={item.disabledAt ? 'default' : 'green'}>{item.disabledAt ? t('disabled') : t('active')}</Tag> },{ title: t('lastLogin'), dataIndex: 'lastLoginAt', render: (value?: string) => formatDateTime(value, i18n.language) },{ title: t('createdAt'), dataIndex: 'createdAt', render: (value: string) => formatDateTime(value, i18n.language) },{ title: '', render: (_: unknown, item: User) => <Button type="text" aria-label={`${t('edit')} ${item.displayName}`} title={t('edit')} icon={<EditOutlined />} onClick={() => show(item)} /> }]} /></Card>
    <Modal title={editing ? `${t('edit')} · ${editing.displayName}` : t('create')} open={open} onCancel={() => setOpen(false)} onOk={() => void save()} confirmLoading={saving} okText={t('save')} destroyOnHidden><Form form={form} layout="vertical" autoComplete="off">{!editing && <Form.Item name="username" label={t('username')} rules={[{ required: true }]}><Input autoComplete="off" data-1p-ignore data-lpignore="true" /></Form.Item>}<Form.Item name="displayName" label={t('displayName')} rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="password" label={editing ? `${t('password')} (${t('leaveEmptyToKeep')})` : t('password')} extra={editing ? t(editing.id === currentUser?.id ? 'passwordResetSelfHint' : 'passwordResetOtherHint') : undefined} rules={editing ? [] : [{ required: true }]}><Input.Password autoComplete="new-password" data-1p-ignore data-lpignore="true" /></Form.Item><Form.Item name="locale" label={t('language')} rules={[{ required: true }]}><Select options={[{ value: 'zh-CN', label: t('languageChinese') }, { value: 'en-US', label: t('languageEnglish') }]} /></Form.Item>{editing && <Form.Item name="disabled" label={t('disabled')} valuePropName="checked" extra={t(editing.id === currentUser?.id ? 'cannotDisableCurrentUser' : 'disableUserHint')}><Switch aria-label={t('disabled')} disabled={editing.id === currentUser?.id} /></Form.Item>}</Form></Modal>
  </>
}
