export interface User { id: string; username: string; displayName: string; locale: string; disabledAt?: string; lastLoginAt?: string; createdAt: string }
export interface Project { id: string; name: string; description: string; color: string; createdAt: string }
export interface Host { id: string; projectId?: string; name: string; sshAddress: string; sshPort: number; sshUser: string; authType: string; hostKey?: string; connectionAddress: string; dataRoot: string; portStart: number; portEnd: number; manageDocker: boolean; os?: string; distro?: string; architecture?: string; dockerVersion?: string; composeVersion?: string; cpuCount: number; memoryBytes: number; diskTotalBytes: number; diskFreeBytes: number; dataRootWritable: boolean; portProbeAvailable: boolean; availablePort: number; status: string; statusMessage?: string; maintenance: boolean; autoRestartDefault: boolean; lastSeenAt?: string; lastCheckedAt?: string; consecutiveFailures: number; labels: Record<string, string>; createdAt: string; updatedAt: string }
export interface Registry { id: string; name: string; url: string; username?: string; hasPassword: boolean; hasCaCertificate: boolean; status: string; statusMessage?: string; statusCode?: number; createdAt: string; updatedAt: string; lastTestedAt?: string }
export interface TemplateVersion { id: string; templateId: string; version: string; imageReference: string; architectures: string[]; minCpu: number; minMemoryBytes: number; minDiskBytes: number; defaultPort: number; manifest: Record<string, unknown>; riskReport: Array<{ code: string; severity: string; message: string }>; createdAt: string }
export interface DatabaseTemplate { id: string; slug: string; name: string; nameZh: string; description: string; category: string; tier: 'standard' | 'experimental' | 'custom'; builtin: boolean; icon: string; riskReport: Array<{ code: string; severity: string; message: string }>; versions: TemplateVersion[] }
export interface Instance { id: string; name: string; projectId?: string; hostId: string; templateVersionId: string; environment: string; labels: Record<string, string>; status: string; statusMessage?: string; desiredState: string; autoRestart: boolean; restartFailures: number; cpu: number; memoryBytes: number; reservedDiskBytes: number; hostPort: number; containerPort: number; bindAddress: string; databaseUsername: string; databaseName: string; configuration?: { extraEnvironment?: Record<string, string>; imageArtifactId?: string | null; registryId?: string | null }; templateSlug: string; templateName: string; templateVersion: string; hostName: string; connectionAddress: string; createdAt: string; updatedAt?: string; lastHealthyAt?: string }
export interface InstanceBackup { id: string; instanceId: string; hostId: string; templateVersionId: string; templateVersion: string; name: string; status: string; sizeBytes: number; sha256?: string; errorMessage?: string; createdBy: string; createdByUsername: string; createdAt: string; completedAt?: string; updatedAt: string }
export interface Task { id: string; kind: string; status: string; resourceType: string; resourceId?: string; hostId?: string; progress: number; stage: string; message: string; errorCode?: string; errorMessage?: string; cancelable: boolean; cancelAsked: boolean; attempts: number; createdAt: string; startedAt?: string; finishedAt?: string; updatedAt?: string }
export interface Alert { id: string; severity: string; type: string; resourceType: string; resourceId: string; title: string; message: string; details?: Record<string, unknown>; status: string; createdAt: string; acknowledgedAt?: string; acknowledgedBy?: string; resolvedAt?: string; resolvedBy?: string }
export interface Webhook { id: string; name: string; url: string; hasSecret: boolean; events: string[]; enabled: boolean; createdAt: string; updatedAt: string; lastDeliveryStatus?: string; lastDeliveryAt?: string; failedDeliveries: number; queuedDeliveries: number }
export interface WebhookDelivery { id: string; webhookId: string; eventId: string; eventType: string; status: string; attempts: number; nextAttemptAt: string; responseStatus?: number; responseBody?: string; errorMessage?: string; createdAt: string; updatedAt: string }
export interface Audit { id: number; userId?: string; username: string; action: string; resourceType: string; resourceId?: string; resourceName: string; ip: string; requestId: string; taskId?: string; result: string; changes: Record<string, unknown>; message: string; createdAt: string }
export interface ImageArtifact { id: string; name: string; filename: string; sizeBytes: number; sha256: string; format: string; imageRefs: string[]; architectures: string[]; status: string; usedByCount: number; createdAt: string; lastUsedAt?: string }

export const bytes = (value?: number): string => {
  if (!value) return '0 B'
  const units = ['B', 'KiB', 'MiB', 'GiB', 'TiB']
  const index = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1)
  return `${(value / 1024 ** index).toFixed(index > 2 ? 1 : 0)} ${units[index]}`
}
